# Generated by Django 3.0.6 on 2020-07-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='chat_default.png', upload_to='chat_images'),
        ),
    ]
