# Generated by Django 3.0.6 on 2020-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color_scheme',
            field=models.CharField(choices=[('red-scheme', 'Red'), ('blue-scheme', 'Blue'), ('green-scheme', 'Green'), ('pink-scheme', 'Pink'), ('purple-scheme', 'Purple'), ('yellow-scheme', 'Yellow')], default='red-scheme', max_length=13),
        ),
    ]
