# Generated by Django 3.0.6 on 2020-06-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_color_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color_scheme',
            field=models.CharField(choices=[('default-scheme', 'Default'), ('red-scheme', 'Red'), ('blue-scheme', 'Blue'), ('green-scheme', 'Green'), ('pink-scheme', 'Pink'), ('purple-scheme', 'Purple'), ('yellow-scheme', 'Yellow')], default='default-scheme', max_length=14),
        ),
    ]
