# Generated by Django 3.0.6 on 2020-06-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20200612_1102'),
        ('blog', '0003_auto_20200611_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='show',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='shows.UpcomingShows'),
        ),
    ]
