# Generated by Django 3.0.6 on 2020-06-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200630_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineproductitem',
            old_name='lineitem_total',
            new_name='productlineitems_total',
        ),
        migrations.RenameField(
            model_name='orderlineticketitem',
            old_name='lineitem_total',
            new_name='ticketlineitems_total',
        ),
    ]
