# Generated by Django 3.0.6 on 2020-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200630_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tickets_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
