# Generated by Django 3.0.6 on 2020-07-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200630_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('deliver', 'deliver'), ('click&collect', 'click&collect')], default='deliver', max_length=32),
        ),
    ]
