# Generated by Django 3.0.6 on 2020-07-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200610_1106'),
        ('checkout', '0007_remove_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('deliver', 'Deliver'), ('click&collect', 'Click&Collect')], default='deliver', max_length=32),
        ),
    ]
