# Generated by Django 3.0.6 on 2020-06-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickCollectLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=40)),
                ('street_address2', models.CharField(max_length=40)),
                ('town_or_city', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=40)),
                ('location_email', models.EmailField(max_length=254)),
                ('location_phone', models.CharField(max_length=40)),
            ],
        ),
    ]
