# Generated by Django 3.0.6 on 2020-06-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('click_and_collect', '0002_auto_20200602_1104'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingshows',
            name='artist_image',
            field=models.ImageField(default='default.jpg', upload_to='shows_images'),
        ),
        migrations.AlterField(
            model_name='upcomingshows',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='click_and_collect.ClickCollectLocations'),
        ),
    ]