# Generated by Django 3.0.6 on 2020-06-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20200612_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingshows',
            name='date',
            field=models.DateField(),
        ),
    ]
