# Generated by Django 3.0.6 on 2020-06-27 12:53
import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20200612_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowsTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(default='', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.UpcomingShows')),
            ],
        ),
    ]
