# Generated by Django 3.0.6 on 2020-06-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_showstickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowsTickets',
        ),
    ]
