# Generated by Django 3.0.6 on 2020-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticket_type',
            field=models.CharField(default='', max_length=40),
        ),
    ]
