# Generated by Django 3.0.6 on 2020-06-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_tickets_ticket_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
