# Generated by Django 3.0.6 on 2020-06-29 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_delete_showstickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowsTickets',
            fields=[
                ('custom_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(default='', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.UpcomingShows')),
            ],
        ),
    ]
