# Generated by Django 3.0.6 on 2020-06-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200604_1024'),
        ('products', '0012_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
