# Generated by Django 3.0.6 on 2020-06-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('image',)},
        ),
    ]
